package io.github.aleksavelickovic.ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import io.github.aleksavelickovic.service.ProcessService;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.List;


public class MainWindow extends JFrame {
    private final ProcessService processService; // Dependecy Injection

    private JPanel mainPanel;
    private JComboBox comboBox;
    private JButton rebootButton;

    public MainWindow(List<String> options, ProcessService processService) {
        this.processService = processService;
        options.addFirst("Fedora Linux");

        setContentPane(mainPanel);
        setLocationRelativeTo(null);
        setSize(640, 360);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);


        comboBox.setModel(new DefaultComboBoxModel<Object>(options.toArray()));
        comboBox.setSelectedIndex(0);

        rebootButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                try {
                    ;
                    rebootButtonOnClick((String) comboBox.getSelectedItem());
                } catch (Exception e) { // TODO change to IOException later
                    throw new RuntimeException(e);
                }
            }
        });

        revalidate();
        repaint();
    }

    public void rebootButtonOnClick(String selectedValue) throws IOException, InterruptedException {
        Process process1 = processService.execute(ProcessService.SET_GRUB, true, "\"" + selectedValue + "\"");

        while (process1.isAlive()) { // TODO
            Thread.sleep(500);
        }

        Process process2 = processService.execute(ProcessService.REBOOT, false, null);

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(3, 5, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.setPreferredSize(new Dimension(1280, 720));
        comboBox = new JComboBox();
        comboBox.setAlignmentY(0.5f);
        comboBox.setAutoscrolls(false);
        comboBox.setForeground(new Color(-16774439));
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        comboBox.setModel(defaultComboBoxModel1);
        comboBox.setName("comboBox");
        mainPanel.add(comboBox, new GridConstraints(1, 1, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, new Dimension(350, 35), new Dimension(350, 35), new Dimension(350, 35), 0, false));
        final Spacer spacer1 = new Spacer();
        mainPanel.add(spacer1, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        mainPanel.add(spacer2, new GridConstraints(1, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        mainPanel.add(spacer3, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer4 = new Spacer();
        mainPanel.add(spacer4, new GridConstraints(0, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        rebootButton = new JButton();
        rebootButton.setText("Reboot");
        mainPanel.add(rebootButton, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
